apiVersion: v1
kind: Pod
metadata:
  name: moviedb
  namespace: blockbuster # or with option -n with kubectl apply
  labels:
    app: moviedb
spec:
  containers:
  - name: moviedb
    image: postgres:17
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
      - name: POSTGRES_PASSWORD
        value: mysuperpassword
      - name: POSTGRES_DB
        valueFrom:
          configMapKeyRef:
            name: db-env
            key: POSTGRES_DB
    # ports:
    #   - containerPort: 5432
