apiVersion: v1
kind: Pod
metadata:
  name: moviedb
  namespace: blockbuster # or with option -n with kubectl apply
  labels:
    app: moviedb
spec:
  containers:
  - name: moviedb
    image: postgres:17
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    env:
      # - name: POSTGRES_PASSWORD
      #   value: mysuperpassword
      - name: POSTGRES_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-secret
            key: DB_PASSWORD
      - name: POSTGRES_USER
        valueFrom:
          secretKeyRef:
            name: db-secret
            key: DB_USER
      - name: POSTGRES_DB
        valueFrom:
          configMapKeyRef:
            name: db-env
            key: POSTGRES_DB
    volumeMounts:
      - mountPath: /docker-entrypoint-initdb.d
        name: db-sql-init
      - mountPath: /var/lib/postgresql/data
        name: db-storage
    # ports:
    #   - containerPort: 5432
  volumes:
    - name: db-sql-init
      configMap: 
        name: db-sql-init
    - name: db-storage
      persistentVolumeClaim:
        claimName: db-pvc
