apiVersion: v1
kind: Service
metadata:
  namespace: blockbuster
  name: moviedb
  labels:
    app: moviedb 
spec:
  selector:
    app: moviedb
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
