apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: blockbuster
  name: db-pvc
spec:
  resources:
    requests:
      storage: 125Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  # storage:
  #   storageclass: csi-hostpath-driver
